# Generated by scripts/update_homebrew.py from verified release checksums.
class Refreshagent < Formula
  desc "Autonomous SEO worker using your local coding agent"
  homepage "https://github.com/RefreshAgent/refreshagent"
  version "0.1.3"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/RefreshAgent/refreshagent/releases/download/v0.1.3/refreshagent-aarch64-apple-darwin"
      sha256 "f6dbc639103e03232bad2cacbb5c93ed5dff81bf59be214d306246a5508d9ee1"
    end
    on_intel do
      url "https://github.com/RefreshAgent/refreshagent/releases/download/v0.1.3/refreshagent-x86_64-apple-darwin"
      sha256 "e0c4bb305db0776da2f3854a2080b48bb1c269c018fe036f5be36f65aa14b0be"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/RefreshAgent/refreshagent/releases/download/v0.1.3/refreshagent-aarch64-unknown-linux-gnu"
      sha256 "62ec2504c482b43cda79fde08174e50f57840ad7ee46283f582d3d5b2b7b3cb4"
    end
    on_intel do
      url "https://github.com/RefreshAgent/refreshagent/releases/download/v0.1.3/refreshagent-x86_64-unknown-linux-gnu"
      sha256 "a9dfb76d3382f043ea890788be4f2d13caa1a2eebfbc06a84994abd3deafe314"
    end
  end

  def install
    binary = Dir["refreshagent-*"].find { |path| File.file?(path) }
    bin.install binary => "refreshagent"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/refreshagent --version")
  end
end
