# Generated by scripts/update_homebrew.py from verified release checksums.
class Refreshagent < Formula
  desc "Autonomous SEO worker using your local coding agent"
  homepage "https://github.com/RefreshAgent/refreshagent"
  version "0.1.2"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/RefreshAgent/refreshagent/releases/download/v0.1.2/refreshagent-aarch64-apple-darwin"
      sha256 "122e0f62b2f307ccdc2d039adbec73be7b62c34a43e4c0410aa8426df6f99658"
    end
    on_intel do
      url "https://github.com/RefreshAgent/refreshagent/releases/download/v0.1.2/refreshagent-x86_64-apple-darwin"
      sha256 "9ccfbd0143933168505bdb65fd69dcbc3f94269b8b86c202ade9cd2cd3005f5b"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/RefreshAgent/refreshagent/releases/download/v0.1.2/refreshagent-aarch64-unknown-linux-gnu"
      sha256 "5591dfe7370ecb93cd83f1b0da9c90420815bf0c6ee68b68b82addff4b526b23"
    end
    on_intel do
      url "https://github.com/RefreshAgent/refreshagent/releases/download/v0.1.2/refreshagent-x86_64-unknown-linux-gnu"
      sha256 "fc08f3642a7ecbde4088b01eec2c336ee26cafa232efb25ce1391aa9a0542e6f"
    end
  end

  def install
    binary = Dir["refreshagent-*"].find { |path| File.file?(path) }
    bin.install binary => "refreshagent"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/refreshagent --version")
  end
end
