#!/usr/bin/env python3
"""Generate a Homebrew formula from published release checksums; no model calls."""
import argparse
import json
import re
import urllib.request
from pathlib import Path

REPO = "https://github.com/RefreshAgent/refreshagent"
TARGETS = ["aarch64-apple-darwin", "x86_64-apple-darwin", "aarch64-unknown-linux-gnu", "x86_64-unknown-linux-gnu"]

def fetch(url):
    request = urllib.request.Request(url, headers={"User-Agent": "refreshagent-homebrew"})
    with urllib.request.urlopen(request, timeout=30) as response:
        return response.read()

def formula(tag, hashes):
    if not re.fullmatch(r"v\d+\.\d+\.\d+", tag):
        raise ValueError("Only stable semantic version tags are supported")
    for target in TARGETS:
        if not re.fullmatch(r"[0-9a-f]{64}", hashes[target]):
            raise ValueError("Invalid SHA-256 checksum")
    def block(target):
        return f'      url "{REPO}/releases/download/{tag}/refreshagent-{target}"\n      sha256 "{hashes[target]}"'
    return f'''# Generated by scripts/update_homebrew.py from verified release checksums.
class Refreshagent < Formula
  desc "Autonomous SEO worker using your local coding agent"
  homepage "{REPO}"
  version "{tag[1:]}"
  license "Apache-2.0"

  on_macos do
    on_arm do
{block(TARGETS[0])}
    end
    on_intel do
{block(TARGETS[1])}
    end
  end
  on_linux do
    on_arm do
{block(TARGETS[2])}
    end
    on_intel do
{block(TARGETS[3])}
    end
  end

  def install
    binary = Dir["refreshagent-*"].find {{ |path| File.file?(path) }}
    bin.install binary => "refreshagent"
  end

  test do
    assert_match version.to_s, shell_output("#{{bin}}/refreshagent --version")
  end
end
'''

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--tag")
    parser.add_argument("--output", default="Formula/refreshagent.rb")
    args = parser.parse_args()
    tag = args.tag or json.loads(fetch("https://api.github.com/repos/RefreshAgent/refreshagent/releases/latest"))["tag_name"]
    if not re.fullmatch(r"v\d+\.\d+\.\d+", tag):
        raise ValueError("Invalid release tag")
    hashes = {}
    for target in TARGETS:
        hashes[target] = fetch(f"{REPO}/releases/download/{tag}/refreshagent-{target}.sha256").decode().split()[0]
    output = Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(formula(tag, hashes))
    print(f"Generated {output} for {tag}")

if __name__ == "__main__":
    main()
